name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  test:
    name: Julia 1.12 - Ubuntu
    runs-on: ubuntu-latest

    env:
      PYTHON: ""
      JULIA_CONDAPKG_BACKEND: Null

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"

      - uses: julia-actions/cache@v2

      - name: Fix PyCall Conda env
        run: |
          julia -e '
            using Pkg
            Pkg.add("Conda")
            Pkg.build("Conda")
            Pkg.add("PyCall")
            ENV["PYTHON"] = ""
            Pkg.build("PyCall")
          '

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Configure Git
        run: |
          git config --global user.name Tester
          git config --global user.email te@st.er

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aero-Spec/Crux.jl
          files: lcov.info
          flags: unittests
