name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  test:
    name: Julia 1.12 - Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"

      # Cache packages, artifacts, registries, compiled cache
      - uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Configure Git
        run: |
          git config --global user.name Tester
          git config --global user.email te@st.er

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Aero-Spec/Crux.jl
          files: lcov.info
          flags: unittests
